# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # Database
  database:
    image: postgres:12.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'main'
      POSTGRES_USER: 'server'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ".psql/data/pgdata:/var/lib/postgresql/data/pgdata"

  # App backend service
  server:
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    expose:
      - 8080
    depends_on:
      - database

  # Frontend service
  web-ui:
    restart: always
    build:
      context: web-ui
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost/api
        BACKEND_NAME: server:8080
    ports:
      - 80:80
    environment:
      - PORT=80
    depends_on:
      - server
