# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.3'

# Define services
services:
  # Database
  database_test:
    image: postgres:12.0
    expose:
      - "5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: coincoinche

  # App backend service
  server_test:
    restart: always
    build:
      context: server
      dockerfile: Dockerfile.test
    ports:
      - 8080:8080
    depends_on:
      - database_test

  # Frontend service
  web-ui_test:
    restart: always
    build:
      context: web-ui
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost/api
        BACKEND_NAME: server:8080
    ports:
      - 80:80
    environment:
      - PORT=80
    depends_on:
      - server_test
